### ISSUE TITLE
The role is not idempotent in CentOS/RedHat 7

### ISSUE THREAD

**Issue by seocam** [linux-system-roles/certificate#45] opened 2020-07-16 13:00 UTC
Running any of `tests/tests_*.yml` more then once keeps returning `changed=1` in CentOS/RedHat 7

The expected result is that after the first run the next executions would have `changed=0`

Reproducible by: 
```
ansible-playbook --become -i <host_ip>, tests/tests_basic_self_signed.ym
```

Recap for first run:
```
PLAY RECAP ***********************************************************************************************
192.168.124.189            : ok=28   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Recap for second (or third...) run:
```
PLAY RECAP ***********************************************************************************************
192.168.124.189            : ok=28   changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by Nihlus** [comment] 2024-01-16 20:29
This issue appears to have returned in at least 1.2.1 (tested with that and 1.3.2) when using the role on Debian 12 under Python 3.11. Certificate requests are not idempotent even with no changes made or necessary, resulting in false-positives on the change notifications.

I was not able to test with the original reproduction since that test appears to no longer be present.

**Comment by richm** [comment] 2024-01-16 20:59
> This issue appears to have returned in at least 1.2.1 (tested with that and 1.3.2) when using the role on Debian 12 under Python 3.11. Certificate requests are not idempotent even with no changes made or necessary, resulting in false-positives on the change notifications.
> 
> I was not able to test with the original reproduction since that test appears to no longer be present.

Is it just the task `Ensure certificate requests` https://github.com/linux-system-roles/certificate/blob/main/tasks/main.yml#L104C9-L104C36 that erroneously reports `changed: true`, or is it other tasks?  Is the role idempotent or not with certain combinations of parameters, or does it not matter?

**Comment by Nihlus** [comment] 2024-01-16 21:35
> Is it just the task `Ensure certificate requests` https://github.com/linux-system-roles/certificate/blob/main/tasks/main.yml#L104C9-L104C36 that erroneously reports `changed: true`, or is it other tasks? Is the role idempotent or not with certain combinations of parameters, or does it not matter?

That's the one, yeah. I've unfortunately not been able to identify a parameter combination that results in idempotent behaviour, but this is how I use the role:

```yml
- include_role:
    name: certificate
    apply:
      become: true
    when: ipaservice_with_certificate | default(true)
```

**Comment by rjeffman** [comment] 2024-01-19 13:54
@Nihlus, @richm I'm having power and connection issues due to a tropical storm that hit my place. It'll take some days for me to look at this issue.

@Nihlus when you say "using the role on Debian 12 under Python 3.11" you mean that the managed node runs Debian 12, right?

**Comment by Nihlus** [comment] 2024-01-19 14:27
Both the controller and the managed node, yeah.

Stay safe!

**Comment by rjeffman** [comment] 2024-01-19 17:56
As the issue is related to Debian 12, and not CentOS/RHEL 7, I created a new issue (#216), and will close this one. Please, let's keep discussion on the new issue.

**Closed by rjeffman** 2024-01-19 17:56 UTC
Labels: bug
